"""
supervisor/schemas.py
----------------------
Shared constants and lightweight types for the supervisor node.

Keeps the node and prompt_builder free of magic strings.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Pipeline stage identifiers
# Each node writes its own stage name to state["pipeline_stage"]
# so the supervisor knows which gate to run.
# ---------------------------------------------------------------------------

class PipelineStage:
    CAD_PARSER          = "cad_parser"
    LOAD_INFERENCE      = "load_inference"
    CLARIFICATION       = "clarification"
    FEATURE_TRANSLATION = "feature_translation"
    ML_PREDICTOR        = "ml_predictor"
    EXPLANATION         = "explanation"


# ---------------------------------------------------------------------------
# Next-node routing constants
# Used in Command(goto=...) — centralised here so a rename is one change.
# ---------------------------------------------------------------------------

class NextNode:
    CAD_PARSER          = "cad_parser"
    LOAD_INFERENCE      = "load_inference"
    CLARIFICATION       = "clarification"
    FEATURE_TRANSLATION = "feature_translation"
    ML_PREDICTOR        = "ml_predictor"
    EXPLANATION         = "explanation"
    REPORT_ASSEMBLY     = "report_assembly"
    END                 = "__end__"


# ---------------------------------------------------------------------------
# Quality gate thresholds
# Centralised so they can be overridden in tests.
# ---------------------------------------------------------------------------

class QualityThresholds:
    # CAD parser
    MIN_TRIANGLE_COUNT: int   = 4
    MIN_VOLUME_MM3:     float = 0.0

    # Load inference
    CONFIDENCE_THRESHOLD:      float = 0.75
    MIN_SAFETY_FACTOR:         float = 1.5
    MAX_LOAD_INFERENCE_RETRIES: int  = 1   # one retry, then abort

    # Feature translation — strength above this is almost certainly a
    # geometry artefact (e.g. t_min fell back to bbox/10 = 0.1 mm)
    MAX_REALISTIC_STRENGTH_MPA: float = 5000.0

    # ML predictor
    MIN_PREDICTION_CONFIDENCE:  float = 0.4
    #MIN_ECO_SCORE_FOR_GOOD_FIT: float = 0.3


# ---------------------------------------------------------------------------
# AbortReason — structured description of why the pipeline was aborted.
# Used as the response_model for the error-message LLM call.
# ---------------------------------------------------------------------------

class AbortReason(BaseModel):
    """
    User-facing explanation of a pipeline abort.
    Generated by the LLM so it reads as natural engineering advice,
    not a stack trace.
    """

    summary: str = Field(
        description=(
            "One sentence describing what went wrong in plain language. "
            "Write for a product design engineer, not a software developer."
        )
    )

    root_cause: str = Field(
        description=(
            "One or two sentences explaining the technical root cause. "
            "Reference the specific value or condition that triggered the abort."
        )
    )

    recommended_action: str = Field(
        description=(
            "One or two sentences telling the user exactly what to fix. "
            "Be specific: 'Re-export the STEP file with tessellation enabled' "
            "is better than 'fix the file'. "
            "If the issue is in the CAD geometry, say what to change in the model. "
            "If the issue is ambiguous object description, say what context to add."
        )
    )
